# Base image for API
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy requirements
COPY requirements.api.txt requirements.txt

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY src/api /app/
# COPY models /app/models
COPY src/models /train_model/

# Expose port
EXPOSE 5000

# Set environment variables
ENV PYTHONUNBUFFERED=1

# Run the application
CMD ["python", "app.py"]
