# Base image for Dashboard
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy requirements
COPY requirements.dashboard.txt requirements.txt

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY src/dashboard /app/

# Expose port
EXPOSE 8050

# Set environment variables
ENV PYTHONUNBUFFERED=1

# Run the application
CMD ["python", "app.py"]
